### ISSUE TITLE
Negative dimension size caused

### ISSUE THREAD

**Issue by Hub-Tian** [hellochick/PSPNet-tensorflow#5]
I am using my own data to train a new PSPNet, but error occured like this. The size of my data is [320,320], and I changed the parameters like INPUT_SIZE = '320,320' and IMG_MEAN. Could you give me some advice about this problem? Thanks!

Traceback (most recent call last):
  File "./train.py", line 216, in <module>
    main()
  File "./train.py", line 121, in main
    net = PSPNet({'data': image_batch}, is_training=True, num_classes=args.num_classes)
  File "/home/tianyl/CCF/PSPNet-tensorflow-master/network.py", line 48, in __init__
    self.setup(is_training, num_classes)
  File "/home/tianyl/CCF/PSPNet-tensorflow-master/model.py", line 439, in setup
    .avg_pool(90, 90, 90, 90, name='conv5_3_pool1')
  File "/home/tianyl/CCF/PSPNet-tensorflow-master/network.py", line 21, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/tianyl/CCF/PSPNet-tensorflow-master/network.py", line 193, in avg_pool
    data_format=DEFAULT_DATAFORMAT)
  File "/home/tianyl/anaconda2/envs/tensorflow1.3/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1744, in avg_pool
    name=name)
  File "/home/tianyl/anaconda2/envs/tensorflow1.3/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 48, in _avg_pool
    data_format=data_format, name=name)
  File "/home/tianyl/anaconda2/envs/tensorflow1.3/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/tianyl/anaconda2/envs/tensorflow1.3/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    set_shapes_for_outputs(ret)
  File "/home/tianyl/anaconda2/envs/tensorflow1.3/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1909, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/tianyl/anaconda2/envs/tensorflow1.3/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1859, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/tianyl/anaconda2/envs/tensorflow1.3/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/tianyl/anaconda2/envs/tensorflow1.3/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 90 from 40 for 'conv5_3_pool1' (op: 'AvgPool') with input shapes: [4,40,40,2048].

**Comment by hellochick** [comment]
Hey, @Hub-Tian. Since the max pooling k_size [90, 90] is designed for input data [713, 713]. (output stride = 8 => 713 / 8). If you want to use [320, 320] as input, you can modify k_size in `model.py`:
```python
        (self.feed('conv5_3/relu')
             .avg_pool(40, 40, 40, 40, name='conv5_3_pool1')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='conv5_3_pool1_conv')
             .batch_normalization(relu=True, name='conv5_3_pool1_conv_bn')
             .resize_bilinear(shape, name='conv5_3_pool1_interp'))

        (self.feed('conv5_3/relu')
             .avg_pool(30, 30, 30, 30, name='conv5_3_pool2')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='conv5_3_pool2_conv')
             .batch_normalization(relu=True, name='conv5_3_pool2_conv_bn')
             .resize_bilinear(shape, name='conv5_3_pool2_interp'))

        (self.feed('conv5_3/relu')
             .avg_pool(20, 20, 20, 20, name='conv5_3_pool3')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='conv5_3_pool3_conv')
             .batch_normalization(relu=True, name='conv5_3_pool3_conv_bn')
             .resize_bilinear(shape, name='conv5_3_pool3_interp'))

        (self.feed('conv5_3/relu')
             .avg_pool(10, 10, 10, 10, name='conv5_3_pool6')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='conv5_3_pool6_conv')
             .batch_normalization(relu=True, name='conv5_3_pool6_conv_bn')
             .resize_bilinear(shape, name='conv5_3_pool6_interp'))
```
If you have other question, feel free to ask me !

**Comment by Hub-Tian** [comment]
It worked after changing the parameters like you said. Thank you so much!

**Comment by smmdream** [comment]
Hello,I use the VOC2012 dateset to test the code,and I reduce the input_size to [480,480] and modify the model.py,the code can run . but there's new problem with my project,such as:

 the first:
step 82 	 loss = 0.103, (0.776 sec/step)
step 83 	 loss = 0.113, (0.776 sec/step)
2017-11-20 11:50:44.143433: W tensorflow/core/framework/op_kernel.cc:1158] Failed precondition: data
2017-11-20 11:50:44.143585: W tensorflow/core/framework/op_kernel.cc:1158] Failed precondition: data
step 84 	 loss = 0.103, (0.781 sec/step)
step 85 	 loss = 0.103, (0.780 sec/step)

the second:
step 114 	 loss = 0.311, (0.840 sec/step)
step 115 	 loss = nan, (0.833 sec/step)
step 116 	 loss = 0.104, (0.804 sec/step)
2017-11-20 11:51:10.301316: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
2017-11-20 11:51:10.301377: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
2017-11-20 11:51:10.301410: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
2017-11-20 11:51:10.301439: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
2017-11-20 11:51:10.301468: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_i

the second error makes the project stop:
OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]


I have no idea how to sovle it,could you help me .thank you very much.
