### ISSUE TITLE
I wanna test my own picture, however ,when I use python inference.py --img-path=./input/indoor -1.jpg --dataset ade20k, it have some wrong ,I really don't know why?

### ISSUE THREAD

**Issue by Kedron007** [hellochick/PSPNet-tensorflow#51]
could anyone help me?
python inference.py --img-path=./input/indoor_1.jpg --dataset ade20k
successful load img: ./input/indoor_1.jpg
WARNING:tensorflow:From /home/nk/PSPNet-tensorflow/tools.py:84: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
2018-10-30 13:01:15.797329: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-30 13:01:15.916037: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-30 13:01:15.916449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.49GiB
2018-10-30 13:01:16.010902: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-30 13:01:16.011750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:02:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2018-10-30 13:01:16.012481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1
2018-10-30 13:01:16.328967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-30 13:01:16.328996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 
2018-10-30 13:01:16.329002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N Y 
2018-10-30 13:01:16.329005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y N 
2018-10-30 13:01:16.329222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10152 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-10-30 13:01:16.329593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10409 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2018-10-30 13:01:16.925429: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "inference.py", line 118, in <module>
    main()
  File "inference.py", line 107, in main
    load(loader, sess, ckpt.model_checkpoint_path)
  File "inference.py", line 50, in load
    saver.restore(sess, ckpt_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1752, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op u'save/RestoreV2', defined at:
  File "inference.py", line 118, in <module>
    main()
  File "inference.py", line 105, in main
    loader = tf.train.Saver(var_list=restore_var)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1284, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1333, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 781, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 400, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 832, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): Read less bytes than requested
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by Kedron007** [comment]
> could anyone help me?
> python inference.py --img-path=./input/indoor_1.jpg --dataset ade20k
> successful load img: ./input/indoor_1.jpg
> WARNING:tensorflow:From /home/nk/PSPNet-tensorflow/tools.py:84: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
> Instructions for updating:
> Use the `axis` argument instead
> 2018-10-30 13:01:15.797329: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2018-10-30 13:01:15.916037: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-10-30 13:01:15.916449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
> pciBusID: 0000:01:00.0
> totalMemory: 10.92GiB freeMemory: 10.49GiB
> 2018-10-30 13:01:16.010902: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-10-30 13:01:16.011750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties:
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
> pciBusID: 0000:02:00.0
> totalMemory: 10.92GiB freeMemory: 10.76GiB
> 2018-10-30 13:01:16.012481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1
> 2018-10-30 13:01:16.328967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-10-30 13:01:16.328996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958] 0 1
> 2018-10-30 13:01:16.329002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0: N Y
> 2018-10-30 13:01:16.329005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1: Y N
> 2018-10-30 13:01:16.329222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10152 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 2018-10-30 13:01:16.329593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10409 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
> 2018-10-30 13:01:16.925429: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read less bytes than requested
> Traceback (most recent call last):
> File "inference.py", line 118, in
> main()
> File "inference.py", line 107, in main
> load(loader, sess, ckpt.model_checkpoint_path)
> File "inference.py", line 50, in load
> saver.restore(sess, ckpt_path)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1752, in restore
> {self.saver_def.filename_tensor_name: save_path})
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
> run_metadata_ptr)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
> feed_dict_tensor, options, run_metadata)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
> run_metadata)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
> [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> Caused by op u'save/RestoreV2', defined at:
> File "inference.py", line 118, in
> main()
> File "inference.py", line 105, in main
> loader = tf.train.Saver(var_list=restore_var)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1284, in **init**
> self.build()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1296, in build
> self._build(self._filename, build_save=True, build_restore=True)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1333, in _build
> build_save=build_save, build_restore=build_restore)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 781, in _build_internal
> restore_sequentially, reshape)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 400, in _AddRestoreOps
> restore_sequentially)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 832, in bulk_restore
> return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
> shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> op_def=op_def)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
> op_def=op_def)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1740, in **init**
> self._traceback = self._graph._extract_stack() # pylint: disable=protected-access
> 
> OutOfRangeError (see above for traceback): Read less bytes than requested
> [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
@hellochick 
Thank you very much for your reply.

**Comment by Hukongtao** [comment]
@Kedron007 the model you restore is wrong? you should restore the model from ade20k
